@startuml

package models {
    abstract class Profile {
        -String name
        -String userType
        -String description
        -String email
        -String password
        -String location
        +void login()
        +void logout()
        +register()
    }

    class Admin {
        -String gender
        +void acceptEnterpriseRegister()
        +searchEveryPortfolio()
        +filterPortfoliyo(age, location)
    }

    class Enterprise {
        -String enterpriseWebURL
        -String enterpriseLogoURL
        +watchVisibleUsers()
        +filterPortfoliyo(age, location)
    }

    class User {
        -workedLocations
        -String username
        -Date birthDate
        -Integer age
        -String gender
        -offerSection
        -portfolio
        -friendList
        -Boolean visibility
        +void editRegister()
        +void addWorkingLocation()
        +void removeWorkingLocation()
        +void addAcademicInfo()
        +void removeAcademicInfo()
        +void removeFriend()
        +void makeFriendRequest()
        +void acceptFriendRequest()
        +void rejectFriendRequest()
        +viewFriendList()
        +viewPortfolio()
    }
}

package controllers {
    class Controller <<controller>> {
    }
}

Controller *-- Profile
Profile <|-- Admin
Profile <|-- User
Profile <|-- Enterprise






@enduml